---
- name: packages grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.3.6_amd64.deb
  register: pkg_grafana

- name: Depack Grafana
  dpkg_selections:
    name: grafana_7.3.6_amd64.deb
    selection: install
  when: pkg_grafana.changed

- name: libfontconfig
  apt:
    name: libfontconfig1
    state: latest
    update_cache: yes

- name: Installgrafana
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: start grafana
  service:
    name: grafana-server
    state: started

- name: Install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes

- name: start prometheus
  service:
    name: prometheus
    state: started

- name: influxdata key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: install influxdb
  apt:
    name: influxdb
    state: latest
    update_cache: yes

- name: start influxdb
  service:
    name: influxdb
    state: started
